[project]
name = "dft-pipeline2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "atomate2",
    "pymatgen",
    "dash-cytoscape>=1.0.2",
    "emmet-core>=0.87.1",
    "jobflow>=0.3.1",
    "jobflow-remote[gui]",
    "mp-api>=0.46.0",
    "pytest>=9.0.3",
    "python-fasthtml<0.13",
    "starlette<0.40",
]

[tool.uv.sources]
atomate2 = { git = "ssh://git@github.com/Luguza/atomate2.git", branch = "exchange-workflow-port-from-atomate1" }
pymatgen = { git = "ssh://git@github.com/Luguza/pymatgen.git", branch = "luguza/heisenberg-mapper-mixed-supercells-4667" }
jobflow-remote = { git = "ssh://git@github.com/Matgenix/jobflow-remote.git", branch = "develop" }